In [4]:
import pandas as pd
df=pd.read_csv("D:/data science/Assignments/Hypothesis/Cutlets.csv")
df

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
df.head()

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522

In [10]:
df.tail()

Unit A  Unit B
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [19]:
import numpy as np
from scipy import stats
from scipy.stats import norm

In [12]:
df["Unit A"].describe()

count    35.000000
mean      7.019091
std       0.288408
min       6.437600
25%       6.831500
50%       6.943800
75%       7.280550
max       7.516900
Name: Unit A, dtype: float64

In [13]:
df["Unit B"].describe()

count    35.000000
mean      6.964297
std       0.343401
min       6.038000
25%       6.753600
50%       6.939900
75%       7.195000
max       7.545900
Name: Unit B, dtype: float64

In [31]:
z,p=stats.ttest_ind(df["Unit A"],df["Unit B"])
print(z,p)

0.7228688704678063 0.4722394724599501


In [32]:
if p<0.05:
    print(" h1 is accepted")
else:
    print("h0  not accepted.")

h0  not accepted.


# Labtat

In [33]:
import pandas as pd
df=pd.read_csv("D:/data science/Assignments/Hypothesis/Labtat.csv")
df

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

In [34]:
df.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [35]:
df.tail()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

In [36]:
df.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [43]:
import scipy.stats as stats
alpha=0.05
fcal,p= stats.f_oneway(df["Laboratory 1"],df["Laboratory 2"],df["Laboratory 3"],df["Laboratory 4"])


In [38]:
fcal

118.70421654401437

In [39]:
p

2.1156708949992414e-57

In [44]:
if p< alpha:
    print("h0 is rejected and h1 is accepted")
else:
    print("h1 is rejected and h0 is accepted")

h0 is rejected and h1 is accepted


# Buyer ratio

In [45]:
import pandas as pd
df=pd.read_csv("D:/data science/Assignments/Hypothesis/BuyerRatio.csv")
df

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [46]:
df.head()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [47]:
df.tail()

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [48]:
df.describe()

East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [61]:
df.drop(['Observed Values'],axis=1,inplace=True)

In [62]:
df

East  West  North  South
0    50   142    131     70
1   435  1523   1356    750

In [63]:
import scipy.stats as stats 
from scipy.stats import chi2_contingency 

In [69]:
p_value=stats.chi2_contingency(df)
p_value

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

In [70]:
if p_value[0]<0.05:
    print("h0 is rejected and h1 is accepted")
else:
    print("h1 is rejected and h0 is accepted")

h1 is rejected and h0 is accepted


In [71]:
if p_value[1]<0.05:
    print("h0 is rejected and h1 is accepted")
else:
    print("h1 is rejected and h0 is accepted")

h1 is rejected and h0 is accepted


In [73]:
import pandas as pd
df=pd.read_csv("D:/data science/Assignments/Hypothesis/Costomer+OrderForm.csv")
df

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [74]:
df.head()

Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [75]:
df.tail()

Phillippines   Indonesia       Malta       India
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

In [79]:
df.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [80]:
df.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [81]:
df.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [82]:
df.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [76]:
df.describe()

Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [78]:
from scipy import stats
from scipy.stats import norm
from scipy.stats import chi2_contingency
import numpy as np

In [87]:
table=np.array([[271,267,269,280],[29,33,31,20]])

In [88]:
table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [94]:
p_value=stats.chi2_contingency(table)
p_value

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [101]:
p_value[1]

0.2771020991233135

In [96]:
if p_value[0]<0.05:
    print("h0 is rejected and h1 is accepted")
else:
    print("h1 is rejected and h0 is accepted")

h1 is rejected and h0 is accepted


In [99]:
if p_value[2]<0.05:
    print("h0 is rejected and h1 is accepted")
else:
    print("h1 is rejected and h0 is accepted")

h1 is rejected and h0 is accepted
